# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependabot :robot:"
    reviewers:
      - "D3strukt0r"
    schedule:
      interval: "weekly" # on monday
      time: "16:00"
      timezone: "Europe/Zurich"

  # macOS pnpm
  - package-ecosystem: "npm"
    directory: "/macOS/Laptop-Personal/Library/pnpm/global/5"
    labels:
      - "dependabot :robot:"
    reviewers:
      - "D3strukt0r"
    schedule:
      interval: "weekly" # on monday
      time: "16:00"
      timezone: "Europe/Zurich"
  - package-ecosystem: "npm"
    directory: "/macOS/Laptop-Work-IWF/Library/pnpm/global/5"
    labels:
      - "dependabot :robot:"
    reviewers:
      - "D3strukt0r"
    schedule:
      interval: "weekly" # on monday
      time: "16:00"
      timezone: "Europe/Zurich"
